import type { APIRoute } from 'astro';
import { getBranches } from '../lib/content';
import { absoluteUrl, localePath } from '../lib/i18n';

/**
 * Sitemap with reciprocal locale alternates (SEO-04, §16.3).
 *
 * Hand-rolled rather than generated by an integration because each entry must
 * carry `xhtml:link` alternates for both locales, and because /order must be
 * excluded — it is noindex and would compete with the branch pages.
 */
const STATIC_ROUTES = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/menu', priority: '0.9', changefreq: 'weekly' },
  { path: '/burgers', priority: '0.8', changefreq: 'monthly' },
  { path: '/breakfast', priority: '0.8', changefreq: 'monthly' },
  { path: '/locations', priority: '0.7', changefreq: 'monthly' },
  { path: '/about', priority: '0.5', changefreq: 'yearly' },
  { path: '/legal/privacy', priority: '0.1', changefreq: 'yearly' },
];

export const GET: APIRoute = async () => {
  const branches = await getBranches();
  const routes = [
    ...STATIC_ROUTES,
    ...branches.map((b) => ({
      path: `/locations/${b.slug}`,
      priority: '0.8',
      changefreq: 'monthly',
    })),
  ];

  const urls = routes
    .flatMap((route) =>
      (['en', 'my'] as const).map((locale) => {
        const alternates = (['en', 'my'] as const)
          .map(
            (alt) =>
              `    <xhtml:link rel="alternate" hreflang="${alt}" href="${absoluteUrl(
                localePath(alt, route.path)
              )}" />`
          )
          .join('\n');
        return `  <url>
    <loc>${absoluteUrl(localePath(locale, route.path))}</loc>
${alternates}
    <xhtml:link rel="alternate" hreflang="x-default" href="${absoluteUrl(
      localePath('en', route.path)
    )}" />
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`;
      })
    )
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls}
</urlset>
`;

  return new Response(xml, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
};
