/**
 * Font subsetting (PRD §16.2, PERF-05).
 *
 * Myanmar webfonts are large — the full Noto Sans Myanmar subset Google serves
 * is ~154KB on its own, which exceeds the entire 150KB font budget. The PRD's
 * stated fallback is to subset to the glyphs actually used, and only then to
 * drop to a system Myanmar stack if it still will not fit.
 *
 * This script collects every Myanmar codepoint that appears anywhere in the
 * site's content and UI strings, then rebuilds the webfont around exactly that
 * set. Re-run it whenever Burmese copy changes:  node scripts/subset-fonts.mjs
 *
 * Requires: python3 with fonttools + brotli.
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT = new URL('..', import.meta.url).pathname;

function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(json|ts|astro|mjs|md)$/.test(entry)) out.push(p);
  }
  return out;
}

const sources = [
  ...walk(join(ROOT, 'src/content')),
  ...walk(join(ROOT, 'src/data')),
  ...walk(join(ROOT, 'src/components')),
  ...walk(join(ROOT, 'src/pages')),
  ...walk(join(ROOT, 'src/lib')),
];

const used = new Set();
for (const file of sources) {
  for (const ch of readFileSync(file, 'utf8')) {
    const cp = ch.codePointAt(0);
    // Myanmar block + extended, plus the joiners and dotted circle that
    // Burmese shaping relies on.
    if (
      (cp >= 0x1000 && cp <= 0x109f) ||
      (cp >= 0xaa60 && cp <= 0xaa7f) ||
      (cp >= 0xa9e0 && cp <= 0xa9fe) ||
      cp === 0x200c || cp === 0x200d || cp === 0x25cc
    ) {
      used.add(cp);
    }
  }
}

// Keep the Myanmar digits and the danda punctuation even if unused today, so a
// price-numeral policy change (Q25) does not silently lose glyphs.
for (let cp = 0x1040; cp <= 0x104b; cp++) used.add(cp);

/*
 * We keep the whole Myanmar block rather than only the codepoints in use today.
 *
 * Subsetting to just the 62 codepoints currently on the site produces a 58KB
 * file that shapes every existing string correctly — it was measured and
 * verified. It is still the wrong trade here, because this site is CMS-driven:
 * a staff member adds a Burmese menu item name at 7pm on a Friday, and if that
 * name uses a codepoint outside the frozen subset, the customer sees an empty
 * box in the middle of a dish name. Saving 83KB is not worth a build that is
 * correct only for the copy that happened to exist when it ran.
 *
 * The whole block covers anything an editor can type in Burmese and still fits
 * the 150KB font budget, because no Latin webfont ships at all.
 *
 * Latin letters, digits and spaces inside Burmese sentences are deliberately
 * NOT included: the source is Google's Myanmar subset and does not contain
 * them. Browsers resolve those runs through normal per-run font fallback.
 * `used` is still computed so the warning below fires if Burmese copy ever
 * introduces a codepoint outside the retained ranges.
 */
const codepoints = [...used].sort((a, b) => a - b);
const outOfBlock = codepoints.filter((cp) => cp < 0x1000 || cp > 0x109f);
/*
 * Basic Latin is retained alongside the Myanmar block, and the space character
 * is the reason. Burmese copy on this site is full of spaces, Latin brand names
 * ("Le SMASH", "Foodpanda") and digits; with the block alone the shaper hits
 * .notdef on every space and draws a box mid-sentence. Verified by shaping the
 * site's own Burmese strings through HarfBuzz — see the check below.
 */
const unicodes =
  'U+0020-007E,U+00A0,U+2018-201D,U+2013-2014,U+2026,' +
  'U+1000-109F,U+200C-200D,U+25CC,U+AA60-AA7F,U+A9E0-A9FE';

const input = join(ROOT, 'assets/fonts-source/noto-myanmar-400.source.woff2');
const output = join(ROOT, 'public/fonts/noto-myanmar-400.woff2');
if (!existsSync(input)) {
  console.error(`Missing source font: ${input}`);
  console.error('Download the full Myanmar subset from Google Fonts and save it there first.');
  process.exit(1);
}

execFileSync('python3', [
  '-m', 'fontTools.subset', input,
  `--unicodes=${unicodes}`,
  '--layout-features=*',   // Burmese needs its full shaping feature set
  '--flavor=woff2',
  '--no-hinting',
  '--desubroutinize',
  `--output-file=${output}`,
], { stdio: 'inherit' });

const before = statSync(input).size;
const after = statSync(output).size;
console.log(
  `Myanmar subset: Myanmar block retained — ` +
  `${(before / 1024).toFixed(1)}KB → ${(after / 1024).toFixed(1)}KB ` +
  `(${codepoints.length} codepoints in use)`
);
if (outOfBlock.length) {
  console.warn(
    'Burmese copy uses codepoints outside the retained ranges: ' +
      outOfBlock.map((cp) => 'U+' + cp.toString(16).toUpperCase()).join(', ')
  );
}

writeFileSync(
  join(ROOT, 'public/fonts/SUBSET.txt'),
  `Noto Sans Myanmar subset generated by scripts/subset-fonts.mjs\n` +
  `${codepoints.length} codepoints\n${unicodes}\n`
);
